### ISSUE TITLE
A few comments

### ISSUE THREAD

**Issue by plafferty64830** [amirito/react-native-password-eye#1]
Hello,

First of all, thank you for creating this brilliant package but I have a few minor suggestions that would make it a little better.

1. 
The prop type for styles should be PropTypes.object instead of PropTypes.arrayOf(PropTypes.object). At present, it forces the user to enter the styles as an array which it a little abnormal. From the RN documentation styles are always entered as object.
I understand why you might have done this, let me explain.
When a CSS style is combined with an inline style we use an array. 
e.g.
`style={[styles.myFancyCssStyle, {backgroundColor: 'white'}]}`

I have tested this change locally and it works as expected. 

2.
A parameter to control the size and colour of the eye icon would be really hand. If your like me, I have a dark background and keen to have the eye the same colour as my text (white).  
Again, I have locally changed this to suit my app but as my colour is fixed I have just amended the icon component. Also, if you want, I'm happy to do a push request for this functionality.

3. 
A ref parameter like TextInput from RN. More often than not, this component is going to be used in a form, probably a signup/login form and the password field usually comes after a username/email field. 
It would be a better UI experience for the end user if the next button moved the cursor straight from the last from field into this component. A ref component is required for this.

4. 
And finally, last but not least, an onSubmitEditing parameter would be really handy.
This is a function that is called when the user touches the returnKey. Default functionality should be a keyboard dismissal but that is not currently possible with the current implementation.

I hope this helps you in some way and the longevity of this package.
I'm more than happy to have a zoom call with you to further discuss this offline.
Please don't hesitate to contact me on LinkedIn - https://www.linkedin.com/in/patrick-lafferty-41aa5210b/. I can share my contact details via LinkedIn, if required, once connected.

Kind Regards
Patrick

**Comment by amirito** [comment]
@plafferty64830 Thank you for your interest and your comment 

I should admit that you are right. I will add these ASAP.

**Comment by plafferty64830** [comment]
No problem and best of luck with the changes.
