### ISSUE TITLE
move {...props} to above other props in TextInput

### ISSUE THREAD

**Issue by dkang23** [amirito/react-native-password-eye#2]
The props are getting rewritten by {...props} at the bottom of the "TextInput". If you put it above the others, this will not happen. As of now, if we set "secureTextEntry = true", we will never be able to see the text even after pressing the eye because the calculated value " secureTextEntry={secureTextEntry ? isSecure : false}" gets overritten

**Comment by amirito** [comment]
@dkang23 Thank you.
I fixed it in `v1.0.5`

**Comment by dkang23** [comment]
works perfectly!
